# 由于版本差距
server:
  port: 8099

#  ssl:
#    enabled-protocols: TLSv1.2,TLSv1.3
spring:
  mvc:
    log-request-details: true
# 本地具体配置

mybatis:
  type-aliases-package: com.example.first_floor.generator.domain
  mapper-locations: classpath:/mapper/*.xml
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml

