
server:
  port: 8099

#  ssl:
#    enabled-protocols: TLSv1.2,TLSv1.3
spring:
  mvc:
    log-request-details: true
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.8.2:1433;databaseName=Data_WaterMeter
    username: sa
    password: Aa123456

mybatis:
  type-aliases-package: com.example.first_floor.generator.domain
  mapper-locations: classpath:/mapper/*.xml
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml

